# Generated by Django 5.1.1 on 2024-10-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_ımdbpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created_date',
            new_name='createdDate',
        ),
    ]
