# Generated by Django 5.1.1 on 2024-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_created_date_movie_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieBanner',
            field=models.ImageField(default='posters/default.jpg', upload_to='posters/'),
        ),
    ]
